'Épice',
'Épice commune',
Épice européenne',
'Vanille',
'Assaisonnement',
'Boisson gazeuse non alcoolisée',
'Coca-cola',
'Limonade',
'Schweppes',
'Soda',
'Boisson gazeuse',
'Fruit à noyau',
'Cerise',
'Pêche',
'Fruit',
'Eau de vie de fruits',
'Alcool de prune',
'Brandy de pommes',
'Cachaça',
'Kirsch',
'Brandy',
'Fruit sec',
'Pistache',